import os
import subprocess
import logging
from typing import Callable, Dict, List, Union


class ProjectIO:
    @staticmethod
    def create_structure(project_path: str, metadata: Dict, logger: Callable[[str], None]):
        try:
            logger("Creating project structure...")
            os.makedirs(project_path, exist_ok=True)

            directories = ['src', 'tests', 'docs', 'config', 'scripts']
            directories.extend(metadata.get('project_structure', []))

            for directory in directories:
                dir_path = os.path.join(project_path, directory)
                try:
                    os.makedirs(dir_path, exist_ok=True)
                    logger(f"Created directory: {dir_path}")
                except OSError as err:
                    logger(f"Warning: Could not create directory {directory}: {err}")

            initial_files = metadata.get('initial_files', {})

            if isinstance(initial_files, dict):
                for filename, content in initial_files.items():
                    ProjectIO._write_file(project_path, filename, content, logger)
            elif isinstance(initial_files, list):
                for entry in initial_files:
                    if isinstance(entry, dict):
                        filename = entry.get('filename') or entry.get('file_name')
                        content = entry.get('content', '')
                        if filename:
                            ProjectIO._write_file(project_path, filename, content, logger)
                    else:
                        logger(f"Warning: Skipping unexpected initial_files item: {entry}")
            else:
                logger("Warning: initial_files format unrecognized.")

            ProjectIO._write_file(project_path, "README.md",
                metadata.get('readme', '# Project Generated by Red-Green-Refactor IDE'),
                logger
            )

        except Exception as e:
            logger(f"Critical error in project structure creation: {e}")
            raise

    @staticmethod
    def _write_file(base_path: str, relative_path: str, content: str, logger: Callable[[str], None]):
        try:
            file_path = os.path.join(base_path, relative_path)
            os.makedirs(os.path.dirname(file_path), exist_ok=True)
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(content or '')
            logger(f"Created file: {file_path}")
        except Exception as e:
            logger(f"Error writing file {relative_path}: {e}")

    @staticmethod
    def write_todo(project_path: str, tasks: Union[List[str], List[Dict[str, str]]], logger: Callable[[str], None]):
        todo_path = os.path.join(project_path, 'TODO.md')
        try:
            with open(todo_path, 'w', encoding='utf-8') as f:
                f.write("# TODO List\n\n")
                for task in tasks:
                    desc = task.get('description') if isinstance(task, dict) else str(task)
                    f.write(f"- [ ] {desc}\n")
            logger("Wrote TODO.md with tasks.")
        except Exception as e:
            logger(f"Error writing TODO list: {e}")

    @staticmethod
    def write_feature_list(project_path: str, features: Dict[str, List[str]], logger: Callable[[str], None]):
        list_path = os.path.join(project_path, 'LIST.md')
        try:
            with open(list_path, 'w', encoding='utf-8') as f:
                f.write("# Feature Tracking\n\n")
                features = features or {'high': ['Initial project setup'], 'medium': [], 'low': []}
                for priority, items in features.items():
                    f.write(f"## {priority.capitalize()} Priority\n")
                    if not items:
                        f.write("- No features defined\n")
                    else:
                        for feat in items:
                            f.write(f"- {feat}\n")
                    f.write("\n")
            logger("Wrote LIST.md with feature tracking.")
        except Exception as e:
            logger(f"Error writing feature list: {e}")

    @staticmethod
    def run_tests(project_path: str, logger: Callable[[str], None]) -> bool:
        logger("Running tests...")
        try:
            result = subprocess.run(
                ['pytest', '--disable-warnings', '--maxfail=1', '-v', '--tb=short'],
                cwd=project_path,
                text=True,
                capture_output=True
            )
            logger(result.stdout)
            if result.stderr:
                logger(f"Test Stderr: {result.stderr}")
            return result.returncode == 0
        except Exception as e:
            logger(f"Critical error running tests: {e}")
            return False
