from sentence_transformers import SentenceTransformer
import sys

# Initialize the model globally to avoid reloading it multiple times
model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')


def get_embeddings(sentences):
    """
    Generate sentence embeddings for the input sentences.

    Args:
        sentences (list or str): List of sentences or a single sentence.

    Returns:
        numpy.ndarray: The embeddings generated by the model.
    """
    # If the input is a string, convert it to a list
    if isinstance(sentences, str):
        sentences = [sentences]

    embeddings = model.encode(sentences)
    return embeddings


def main():
    """
    Main function to handle command-line input.
    Expects a list of sentences as input.
    """
    # Join command-line arguments as a single sentence
    sentences = sys.argv[1:]
    if not sentences:
        print("Please provide at least one sentence as input.")
        sys.exit(1)

    embeddings = get_embeddings(sentences)
    print(embeddings)


# Allow the script to be used both as a module and as a standalone script
if __name__ == '__main__':
    main()
