from sentence_transformers import SentenceTransformer
from transformers import AutoTokenizer, AutoModel
import torch
import sys

model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")


def get_embeddings(sentences):
    """ ""\"
    ""\"
    Generate sentence embeddings for the input sentences.

    Args:
        sentences (list or str): List of sentences or a single sentence.

    Returns:
        numpy.ndarray: The embeddings generated by the model.
    ""\"
    ""\" """
    if isinstance(sentences, str):
        sentences = [sentences]
    embeddings = model.encode(sentences)
    return embeddings


def generate_embedding(content):
    tokenizer = AutoTokenizer.from_pretrained('sentence-transformers/all-MiniLM-L6-v2')
    model = AutoModel.from_pretrained('sentence-transformers/all-MiniLM-L6-v2')

    inputs = tokenizer(content, return_tensors='pt', padding=True, truncation=True, max_length=512)
    outputs = model(**inputs)
    embeddings = outputs.last_hidden_state.mean(dim=1)
    return embeddings.detach().numpy().tolist()


def main():
    """ ""\"
    ""\"
    Main function to handle command-line input.
    Expects a list of sentences as input.
    ""\"
    ""\" """
    sentences = sys.argv[1:]
    if not sentences:
        print("Please provide at least one sentence as input.")
        sys.exit(1)
    embeddings = get_embeddings(sentences)
    print(embeddings)


if __name__ == "__main__":
    main()
